/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoomAssignment;

import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author solve
 */
public class Add_Room extends javax.swing.JFrame {

    /**
     * Creates new form Add_Room
     */
    public Add_Room() {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpStartTime = new com.raven.swing.TimePicker();
        tpEndTime = new com.raven.swing.TimePicker();
        pnlAddNewRoomSchedule = new javax.swing.JPanel();
        txtEndTime = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblSection = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        lblDayOfTheWeek = new javax.swing.JLabel();
        txtSection = new javax.swing.JTextField();
        lblStartTime = new javax.swing.JLabel();
        btnStartTime = new javax.swing.JButton();
        btnEndTime = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        txtDayOfTheWeek = new javax.swing.JTextField();
        txtStartTime = new javax.swing.JTextField();
        lblRoom = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();

        tpStartTime.setForeground(new java.awt.Color(218, 104, 70));
        tpStartTime.setDisplayText(txtStartTime);
        tpStartTime.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tpEndTime.setForeground(new java.awt.Color(218, 104, 70));
        tpEndTime.setDisplayText(txtEndTime);
        tpEndTime.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(309, 402));
        setName("Add New Room Schedule"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        pnlAddNewRoomSchedule.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Room Schedule", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 3, 14))); // NOI18N

        txtEndTime.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblID.setText("ID");

        lblEndTime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblEndTime.setText("End Time");

        lblSubject.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSubject.setText("Subject");

        txtID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblSection.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblSection.setText("Section");

        txtSubject.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblDayOfTheWeek.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblDayOfTheWeek.setText("Day of the Week");

        txtSection.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblStartTime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblStartTime.setText("Start Time");

        btnStartTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/clock.png"))); // NOI18N
        btnStartTime.setBorder(null);
        btnStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartTimeActionPerformed(evt);
            }
        });

        btnEndTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/clock.png"))); // NOI18N
        btnEndTime.setBorder(null);
        btnEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndTimeActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(218, 104, 70));
        btnCancel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(218, 104, 70));
        btnSave.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnSave.setText("Add");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblError.setForeground(java.awt.Color.red);
        lblError.setText("[error appear here]");

        txtDayOfTheWeek.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtStartTime.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtStartTime.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtStartTimeInputMethodTextChanged(evt);
            }
        });

        lblRoom.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblRoom.setText("Room");

        txtRoom.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlAddNewRoomScheduleLayout = new javax.swing.GroupLayout(pnlAddNewRoomSchedule);
        pnlAddNewRoomSchedule.setLayout(pnlAddNewRoomScheduleLayout);
        pnlAddNewRoomScheduleLayout.setHorizontalGroup(
            pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                        .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoom)
                            .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                        .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                                .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEndTime))
                            .addComponent(lblEndTime)
                            .addComponent(lblError)
                            .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                                .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSection)
                                    .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStartTime)
                                    .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                                        .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnStartTime))
                                    .addComponent(lblDayOfTheWeek)
                                    .addComponent(txtDayOfTheWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSubject))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAddNewRoomScheduleLayout.setVerticalGroup(
            pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                        .addComponent(lblRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                        .addComponent(lblSection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddNewRoomScheduleLayout.createSequentialGroup()
                        .addComponent(lblSubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDayOfTheWeek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDayOfTheWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStartTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStartTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEndTime)
                    .addComponent(btnEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewRoomScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAddNewRoomSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAddNewRoomSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTimeActionPerformed
        tpStartTime.showPopup(this, 100, 100);
    }//GEN-LAST:event_btnStartTimeActionPerformed

    private void btnEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndTimeActionPerformed
        tpEndTime.showPopup(this, 100, 100);
    }//GEN-LAST:event_btnEndTimeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtStartTimeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtStartTimeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartTimeInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEndTime;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStartTime;
    private javax.swing.JLabel lblDayOfTheWeek;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JPanel pnlAddNewRoomSchedule;
    private com.raven.swing.TimePicker tpEndTime;
    private com.raven.swing.TimePicker tpStartTime;
    private javax.swing.JTextField txtDayOfTheWeek;
    private javax.swing.JTextField txtEndTime;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtRoom;
    private javax.swing.JTextField txtSection;
    private javax.swing.JTextField txtStartTime;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
