/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoomAssignment;

import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author solve
 */
public class Add_Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Add_Teacher
     */
    public Add_Teacher() {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddNewTeacher = new javax.swing.JPanel();
        txtID1 = new javax.swing.JTextField();
        txtUsername1 = new javax.swing.JTextField();
        txtFirstName1 = new javax.swing.JTextField();
        txtMiddleName = new javax.swing.JTextField();
        txtLastName1 = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        lblPassword1 = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        pfPassword1 = new javax.swing.JPasswordField();
        lblUsername1 = new javax.swing.JLabel();
        lblConfirmPassword1 = new javax.swing.JLabel();
        pfConfirmPassword1 = new javax.swing.JPasswordField();
        lblFirstName1 = new javax.swing.JLabel();
        cbShowPassword1 = new javax.swing.JCheckBox();
        lblError1 = new javax.swing.JLabel();
        lblLastName1 = new javax.swing.JLabel();
        lblMiddleName = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Add New Teacher"); // NOI18N
        setUndecorated(true);

        pnlAddNewTeacher.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Teacher", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 3, 14))); // NOI18N

        txtID1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtUsername1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtFirstName1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtMiddleName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtLastName1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtDepartment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtContact.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtAddress.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(218, 104, 70));
        btnAdd.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel1.setBackground(new java.awt.Color(218, 104, 70));
        btnCancel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCancel1.setText("Cancel");
        btnCancel1.setBorder(null);
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        lblPassword1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblPassword1.setText("Password");

        lblContact.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblContact.setText("Contact");

        lblID1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblID1.setText("ID");

        lblAddress.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblAddress.setText("Address");

        pfPassword1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pfPassword1.setText("jPasswordField1");

        lblUsername1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblUsername1.setText("Username");

        lblConfirmPassword1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblConfirmPassword1.setText("Confirm Password");

        pfConfirmPassword1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pfConfirmPassword1.setText("jPasswordField1");

        lblFirstName1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblFirstName1.setText("First Name");

        cbShowPassword1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbShowPassword1.setText("Show Password");
        cbShowPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPassword1ActionPerformed(evt);
            }
        });

        lblError1.setForeground(java.awt.Color.red);
        lblError1.setText("[error appear here]");

        lblLastName1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblLastName1.setText("Last Name");

        lblMiddleName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMiddleName.setText("Middle Name");

        lblDepartment.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblDepartment.setText("Department");

        lblEmail.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblEmail.setText("Email");

        javax.swing.GroupLayout pnlAddNewTeacherLayout = new javax.swing.GroupLayout(pnlAddNewTeacher);
        pnlAddNewTeacher.setLayout(pnlAddNewTeacherLayout);
        pnlAddNewTeacherLayout.setHorizontalGroup(
            pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNewTeacherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbShowPassword1)
                    .addGroup(pnlAddNewTeacherLayout.createSequentialGroup()
                        .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername1)
                            .addComponent(lblID1))
                        .addGap(25, 25, 25)
                        .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAddress)
                    .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlAddNewTeacherLayout.createSequentialGroup()
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddNewTeacherLayout.createSequentialGroup()
                            .addComponent(lblConfirmPassword1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pfConfirmPassword1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddNewTeacherLayout.createSequentialGroup()
                            .addComponent(lblPassword1)
                            .addGap(52, 52, 52)
                            .addComponent(pfPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddNewTeacherLayout.createSequentialGroup()
                            .addComponent(lblFirstName1)
                            .addGap(24, 24, 24)
                            .addComponent(txtFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddNewTeacherLayout.createSequentialGroup()
                            .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMiddleName)
                                .addComponent(lblLastName1)
                                .addComponent(lblDepartment)
                                .addComponent(lblEmail)
                                .addComponent(lblContact))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDepartment)
                                .addComponent(txtMiddleName)
                                .addComponent(txtLastName1)
                                .addComponent(txtEmail)
                                .addComponent(txtContact))))
                    .addComponent(lblError1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAddNewTeacherLayout.setVerticalGroup(
            pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNewTeacherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID1)
                    .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername1)
                    .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName1)
                    .addComponent(txtFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMiddleName)
                    .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName1)
                    .addComponent(txtLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword1)
                    .addComponent(pfPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmPassword1)
                    .addComponent(pfConfirmPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbShowPassword1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddNewTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAddNewTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAddNewTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void cbShowPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPassword1ActionPerformed
         if(cbShowPassword1.isSelected()){
            pfPassword1.setEchoChar((char) 0);
            pfConfirmPassword1.setEchoChar((char) 0);
        }else{
            pfPassword1.setEchoChar('*');
            pfConfirmPassword1.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowPassword1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JCheckBox cbShowPassword1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblConfirmPassword1;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JLabel lblMiddleName;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JPasswordField pfConfirmPassword1;
    private javax.swing.JPasswordField pfPassword1;
    private javax.swing.JPanel pnlAddNewTeacher;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName1;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtLastName1;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
