/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoomAssignment;

/**
 *
 * @author solve
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlNavigator = new javax.swing.JPanel();
        btnRoomManagement = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblDashboardText = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnAccount = new javax.swing.JButton();
        lblWelcomeUser = new javax.swing.JLabel();
        btnMembers = new javax.swing.JButton();
        pnlNavigatorPanel = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setName("Dashboard"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);

        pnlNavigator.setBackground(new java.awt.Color(205, 203, 214));
        pnlNavigator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRoomManagement.setBackground(new java.awt.Color(218, 104, 70));
        btnRoomManagement.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRoomManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/lecture.png"))); // NOI18N
        btnRoomManagement.setText("Room Management");
        btnRoomManagement.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRoomManagement.setBorderPainted(false);
        pnlNavigator.add(btnRoomManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, 330, 50));

        btnHome.setBackground(new java.awt.Color(218, 104, 70));
        btnHome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/home.png"))); // NOI18N
        btnHome.setToolTipText("");
        btnHome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnHome.setBorderPainted(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHome.setLabel("Home");
        pnlNavigator.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 110, 330, 50));

        lblDashboardText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblDashboardText.setText("Dashboard");
        pnlNavigator.add(lblDashboardText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblDate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblDate.setText("Date: [real-time and date]");
        pnlNavigator.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        btnAccount.setBackground(new java.awt.Color(218, 104, 70));
        btnAccount.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/user.png"))); // NOI18N
        btnAccount.setText("Account");
        btnAccount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAccount.setBorderPainted(false);
        pnlNavigator.add(btnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 330, 50));

        lblWelcomeUser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblWelcomeUser.setText("Welcome, [name of librarian]");
        pnlNavigator.add(lblWelcomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnMembers.setBackground(new java.awt.Color(218, 104, 70));
        btnMembers.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/group.png"))); // NOI18N
        btnMembers.setText("Members");
        btnMembers.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMembers.setBorderPainted(false);
        pnlNavigator.add(btnMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 210, 330, 50));

        pnlNavigatorPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlNavigatorPanelLayout = new javax.swing.GroupLayout(pnlNavigatorPanel);
        pnlNavigatorPanel.setLayout(pnlNavigatorPanelLayout);
        pnlNavigatorPanelLayout.setHorizontalGroup(
            pnlNavigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNavigatorPanelLayout.setVerticalGroup(
            pnlNavigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNavigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNavigatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMembers;
    private javax.swing.JButton btnRoomManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDashboardText;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblWelcomeUser;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlNavigator;
    private javax.swing.JPanel pnlNavigatorPanel;
    // End of variables declaration//GEN-END:variables
}
