/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoomAssignment;

import java.awt.Color;

/**
 *
 * @author solve
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pnlTabLeft = new javax.swing.JPanel();
        pnlTabHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        pnlTabRoomManagement = new javax.swing.JPanel();
        lblTabRoomManagement = new javax.swing.JLabel();
        pnlTabMembers = new javax.swing.JPanel();
        lblTabMembers = new javax.swing.JLabel();
        pnlTabAccount = new javax.swing.JPanel();
        lblTabAccount = new javax.swing.JLabel();
        lblWelcomeUser = new javax.swing.JLabel();
        pnlTabRight = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlCreatedSchedule = new javax.swing.JPanel();
        lblCreatedSchedule = new javax.swing.JLabel();
        lblScheduleNumber = new javax.swing.JLabel();
        pnlCreatedAccount = new javax.swing.JPanel();
        lblCreatedAccount = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        pnlFacultiesStudents = new javax.swing.JPanel();
        lblFaculties = new javax.swing.JLabel();
        lblStudents = new javax.swing.JLabel();
        lblFacultiesNumber = new javax.swing.JLabel();
        lblStudentsNumber = new javax.swing.JLabel();
        pnlRoomManagement = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        pnlMembers = new javax.swing.JPanel();
        pnlAccount = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("Dashboard"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);

        pnlTabLeft.setBackground(java.awt.Color.white);

        pnlTabHome.setBackground(new java.awt.Color(218, 104, 70));
        pnlTabHome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTabHome.setPreferredSize(new java.awt.Dimension(105, 55));
        pnlTabHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTabHomeMouseClicked(evt);
            }
        });

        lblHome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/home.png"))); // NOI18N
        lblHome.setText("Home");

        javax.swing.GroupLayout pnlTabHomeLayout = new javax.swing.GroupLayout(pnlTabHome);
        pnlTabHome.setLayout(pnlTabHomeLayout);
        pnlTabHomeLayout.setHorizontalGroup(
            pnlTabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTabHomeLayout.setVerticalGroup(
            pnlTabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTabRoomManagement.setBackground(new java.awt.Color(218, 104, 70));
        pnlTabRoomManagement.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTabRoomManagement.setPreferredSize(new java.awt.Dimension(105, 55));
        pnlTabRoomManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTabRoomManagementMouseClicked(evt);
            }
        });

        lblTabRoomManagement.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTabRoomManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabRoomManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/lecture.png"))); // NOI18N
        lblTabRoomManagement.setText("Room Management");

        javax.swing.GroupLayout pnlTabRoomManagementLayout = new javax.swing.GroupLayout(pnlTabRoomManagement);
        pnlTabRoomManagement.setLayout(pnlTabRoomManagementLayout);
        pnlTabRoomManagementLayout.setHorizontalGroup(
            pnlTabRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabRoomManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTabRoomManagementLayout.setVerticalGroup(
            pnlTabRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabRoomManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTabMembers.setBackground(new java.awt.Color(218, 104, 70));
        pnlTabMembers.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTabMembers.setPreferredSize(new java.awt.Dimension(105, 55));
        pnlTabMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTabMembersMouseClicked(evt);
            }
        });

        lblTabMembers.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTabMembers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/group.png"))); // NOI18N
        lblTabMembers.setText("Members");

        javax.swing.GroupLayout pnlTabMembersLayout = new javax.swing.GroupLayout(pnlTabMembers);
        pnlTabMembers.setLayout(pnlTabMembersLayout);
        pnlTabMembersLayout.setHorizontalGroup(
            pnlTabMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTabMembersLayout.setVerticalGroup(
            pnlTabMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTabAccount.setBackground(new java.awt.Color(218, 104, 70));
        pnlTabAccount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTabAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTabAccountMouseClicked(evt);
            }
        });

        lblTabAccount.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTabAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/user.png"))); // NOI18N
        lblTabAccount.setText("Account");

        javax.swing.GroupLayout pnlTabAccountLayout = new javax.swing.GroupLayout(pnlTabAccount);
        pnlTabAccount.setLayout(pnlTabAccountLayout);
        pnlTabAccountLayout.setHorizontalGroup(
            pnlTabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTabAccountLayout.setVerticalGroup(
            pnlTabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblWelcomeUser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblWelcomeUser.setText("Welcome, [username]");

        javax.swing.GroupLayout pnlTabLeftLayout = new javax.swing.GroupLayout(pnlTabLeft);
        pnlTabLeft.setLayout(pnlTabLeftLayout);
        pnlTabLeftLayout.setHorizontalGroup(
            pnlTabLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTabHome, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addComponent(pnlTabRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addComponent(pnlTabMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addComponent(pnlTabAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlTabLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcomeUser)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnlTabLeftLayout.setVerticalGroup(
            pnlTabLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabLeftLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblWelcomeUser)
                .addGap(52, 52, 52)
                .addComponent(pnlTabHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabRoomManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabMembers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pnlTabRight.setBackground(new java.awt.Color(204, 204, 204));

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));

        pnlCreatedSchedule.setBackground(java.awt.Color.darkGray);

        lblCreatedSchedule.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCreatedSchedule.setForeground(java.awt.Color.white);
        lblCreatedSchedule.setText("Created Schedule");

        lblScheduleNumber.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblScheduleNumber.setForeground(java.awt.Color.white);
        lblScheduleNumber.setText("00");

        javax.swing.GroupLayout pnlCreatedScheduleLayout = new javax.swing.GroupLayout(pnlCreatedSchedule);
        pnlCreatedSchedule.setLayout(pnlCreatedScheduleLayout);
        pnlCreatedScheduleLayout.setHorizontalGroup(
            pnlCreatedScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreatedScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCreatedScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScheduleNumber)
                    .addComponent(lblCreatedSchedule))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        pnlCreatedScheduleLayout.setVerticalGroup(
            pnlCreatedScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreatedScheduleLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblScheduleNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreatedSchedule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCreatedAccount.setBackground(java.awt.Color.darkGray);

        lblCreatedAccount.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCreatedAccount.setForeground(java.awt.Color.white);
        lblCreatedAccount.setText("Created Account");

        lblAccountNumber.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblAccountNumber.setForeground(java.awt.Color.white);
        lblAccountNumber.setText("00");

        javax.swing.GroupLayout pnlCreatedAccountLayout = new javax.swing.GroupLayout(pnlCreatedAccount);
        pnlCreatedAccount.setLayout(pnlCreatedAccountLayout);
        pnlCreatedAccountLayout.setHorizontalGroup(
            pnlCreatedAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreatedAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCreatedAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccountNumber)
                    .addComponent(lblCreatedAccount))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnlCreatedAccountLayout.setVerticalGroup(
            pnlCreatedAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreatedAccountLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblAccountNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreatedAccount)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pnlFacultiesStudents.setBackground(java.awt.Color.darkGray);

        lblFaculties.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblFaculties.setForeground(java.awt.Color.white);
        lblFaculties.setText("Faculties");

        lblStudents.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblStudents.setForeground(java.awt.Color.white);
        lblStudents.setText("Students");

        lblFacultiesNumber.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblFacultiesNumber.setForeground(java.awt.Color.white);
        lblFacultiesNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacultiesNumber.setText("00");

        lblStudentsNumber.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblStudentsNumber.setForeground(java.awt.Color.white);
        lblStudentsNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentsNumber.setText("00");

        javax.swing.GroupLayout pnlFacultiesStudentsLayout = new javax.swing.GroupLayout(pnlFacultiesStudents);
        pnlFacultiesStudents.setLayout(pnlFacultiesStudentsLayout);
        pnlFacultiesStudentsLayout.setHorizontalGroup(
            pnlFacultiesStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacultiesStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFacultiesStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStudentsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFacultiesStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblFacultiesNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFaculties, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStudents, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        pnlFacultiesStudentsLayout.setVerticalGroup(
            pnlFacultiesStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacultiesStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFacultiesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFaculties)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStudentsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStudents)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlFacultiesStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlCreatedSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCreatedAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCreatedAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCreatedSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFacultiesStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRoomManagement.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Room Management");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("UserID");

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField1.setText("000");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Name");

        jTextField2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Status");

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Instructor", "Student" }));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Room Number");

        jTextField3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlRoomManagementLayout = new javax.swing.GroupLayout(pnlRoomManagement);
        pnlRoomManagement.setLayout(pnlRoomManagementLayout);
        pnlRoomManagementLayout.setHorizontalGroup(
            pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRoomManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addGroup(pnlRoomManagementLayout.createSequentialGroup()
                        .addGroup(pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addGroup(pnlRoomManagementLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1))
                                .addGroup(pnlRoomManagementLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField2))
                                .addGroup(pnlRoomManagementLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlRoomManagementLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlRoomManagementLayout.setVerticalGroup(
            pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRoomManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlMembers.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout pnlMembersLayout = new javax.swing.GroupLayout(pnlMembers);
        pnlMembers.setLayout(pnlMembersLayout);
        pnlMembersLayout.setHorizontalGroup(
            pnlMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        pnlMembersLayout.setVerticalGroup(
            pnlMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        pnlAccount.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout pnlAccountLayout = new javax.swing.GroupLayout(pnlAccount);
        pnlAccount.setLayout(pnlAccountLayout);
        pnlAccountLayout.setHorizontalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        pnlAccountLayout.setVerticalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlTabRightLayout = new javax.swing.GroupLayout(pnlTabRight);
        pnlTabRight.setLayout(pnlTabRightLayout);
        pnlTabRightLayout.setHorizontalGroup(
            pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlTabRightLayout.setVerticalGroup(
            pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTabLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTabLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTabRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTabHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTabHomeMouseClicked
        pnlHome.setVisible(true);
        pnlRoomManagement.setVisible(false);
        pnlMembers.setVisible(false);
        pnlAccount.setVisible(false);
        
        pnlTabHome.setBackground(new Color(247, 246, 220));
        pnlTabRoomManagement.setBackground(new Color(218,104,70));
        pnlTabMembers.setBackground(new Color(218,104,70));
        pnlTabAccount.setBackground(new Color(218,104,70));
    }//GEN-LAST:event_pnlTabHomeMouseClicked

    private void pnlTabRoomManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTabRoomManagementMouseClicked
        pnlRoomManagement.setVisible(true);
        pnlHome.setVisible(false);
        pnlMembers.setVisible(false);
        pnlAccount.setVisible(false);
        
        pnlTabRoomManagement.setBackground(new Color(247, 246, 220));
        pnlTabHome.setBackground(new Color(218,104,70));
        pnlTabMembers.setBackground(new Color(218,104,70));
        pnlTabAccount.setBackground(new Color(218,104,70));
    }//GEN-LAST:event_pnlTabRoomManagementMouseClicked

    private void pnlTabMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTabMembersMouseClicked
        pnlMembers.setVisible(true);
        pnlHome.setVisible(false);
        pnlRoomManagement.setVisible(false);
        pnlAccount.setVisible(false);
        
        pnlTabMembers.setBackground(new Color(247, 246, 220));
        pnlTabHome.setBackground(new Color(218,104,70));
        pnlTabRoomManagement.setBackground(new Color(218,104,70));
        pnlTabAccount.setBackground(new Color(218,104,70));
    }//GEN-LAST:event_pnlTabMembersMouseClicked

    private void pnlTabAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTabAccountMouseClicked
        pnlAccount.setVisible(true);
        pnlHome.setVisible(false);
        pnlRoomManagement.setVisible(false);
        pnlMembers.setVisible(false);
        
        pnlTabAccount.setBackground(new Color(247, 246, 220));
        pnlTabHome.setBackground(new Color(218,104,70));
        pnlTabRoomManagement.setBackground(new Color(218,104,70));
        pnlTabMembers.setBackground(new Color(218,104,70));
    }//GEN-LAST:event_pnlTabAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblCreatedAccount;
    private javax.swing.JLabel lblCreatedSchedule;
    private javax.swing.JLabel lblFaculties;
    private javax.swing.JLabel lblFacultiesNumber;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblScheduleNumber;
    private javax.swing.JLabel lblStudents;
    private javax.swing.JLabel lblStudentsNumber;
    private javax.swing.JLabel lblTabAccount;
    private javax.swing.JLabel lblTabMembers;
    private javax.swing.JLabel lblTabRoomManagement;
    private javax.swing.JLabel lblWelcomeUser;
    private javax.swing.JPanel pnlAccount;
    private javax.swing.JPanel pnlCreatedAccount;
    private javax.swing.JPanel pnlCreatedSchedule;
    private javax.swing.JPanel pnlFacultiesStudents;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlMembers;
    private javax.swing.JPanel pnlRoomManagement;
    private javax.swing.JPanel pnlTabAccount;
    private javax.swing.JPanel pnlTabHome;
    private javax.swing.JPanel pnlTabLeft;
    private javax.swing.JPanel pnlTabMembers;
    private javax.swing.JPanel pnlTabRight;
    private javax.swing.JPanel pnlTabRoomManagement;
    // End of variables declaration//GEN-END:variables
}
