/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoomAssignment;

import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author solve
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        DefaultTab();
        
        //Rounded Corner
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpRAMStartTime = new com.raven.swing.TimePicker();
        tpRAMEndTime = new com.raven.swing.TimePicker();
        pnlTabLeft = new javax.swing.JPanel();
        pnlTabHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        pnlTabRoomManagement = new javax.swing.JPanel();
        lblTabRoomManagement = new javax.swing.JLabel();
        pnlTabMembers = new javax.swing.JPanel();
        lblTabMembers = new javax.swing.JLabel();
        pnlTabAccount = new javax.swing.JPanel();
        lblTabAccount = new javax.swing.JLabel();
        lblImageOnTop = new javax.swing.JLabel();
        lblRoomMangementSystem = new javax.swing.JLabel();
        pnlTabRight = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlHomeCreatedSchedule = new javax.swing.JPanel();
        lblHomeCreatedSchedule = new javax.swing.JLabel();
        lblHomeScheduleNumber = new javax.swing.JLabel();
        pnlHomeCreatedAccount = new javax.swing.JPanel();
        lblHomeCreatedAccount = new javax.swing.JLabel();
        lblHomeAccountNumber = new javax.swing.JLabel();
        pnlHomeFacultiesStudents = new javax.swing.JPanel();
        lblHomeFaculties = new javax.swing.JLabel();
        lblHomeFacultiesNumber = new javax.swing.JLabel();
        pnlHomeActivityLog = new javax.swing.JPanel();
        spActivityLog = new javax.swing.JScrollPane();
        listActivityLog = new javax.swing.JList<>();
        pnlRoomManagement = new javax.swing.JPanel();
        lblRAMRoomManagement = new javax.swing.JLabel();
        pnlRAMSchedule = new javax.swing.JPanel();
        spRAMShowRoom = new javax.swing.JScrollPane();
        tblRAMShowRoom = new javax.swing.JTable();
        lblRAMID = new javax.swing.JLabel();
        lblRAMSubject = new javax.swing.JLabel();
        lblRAMSection = new javax.swing.JLabel();
        lblRAMDayOfTheWeek = new javax.swing.JLabel();
        lblRAMStartTime = new javax.swing.JLabel();
        lblRAMEndTime = new javax.swing.JLabel();
        txtRAMID = new javax.swing.JTextField();
        txtRAMSubject = new javax.swing.JTextField();
        txtRAMSection = new javax.swing.JTextField();
        btnRAMSave = new javax.swing.JButton();
        btnRAMAddNew = new javax.swing.JButton();
        txtRAMStartTime = new javax.swing.JTextField();
        txtRAMEndTime = new javax.swing.JTextField();
        btnRAMStartTime = new javax.swing.JButton();
        btnRAMEndTime = new javax.swing.JButton();
        lblRAMError = new javax.swing.JLabel();
        btnRAMDeleteRoom = new javax.swing.JButton();
        lblRAMRoom = new javax.swing.JLabel();
        txtRAMRoom = new javax.swing.JTextField();
        cbRAMDayOfTheWeek = new javax.swing.JComboBox<>();
        lblRAMTeacher = new javax.swing.JLabel();
        txtRAMTeacher = new javax.swing.JTextField();
        btnRAMEdit = new javax.swing.JButton();
        txtRAMSearch = new javax.swing.JTextField();
        btnRAMSearch = new javax.swing.JButton();
        pnlMembers = new javax.swing.JPanel();
        lblMMember = new javax.swing.JLabel();
        pnlMViewUser = new javax.swing.JPanel();
        lblMUserFirstName = new javax.swing.JLabel();
        lblMUserLastName = new javax.swing.JLabel();
        lblMUserPassword = new javax.swing.JLabel();
        txtMUserID = new javax.swing.JTextField();
        btnMUserSave = new javax.swing.JButton();
        txtMUserUsername = new javax.swing.JTextField();
        txtMUserFirstName = new javax.swing.JTextField();
        txtMUserLastName = new javax.swing.JTextField();
        btnMUserAddNew = new javax.swing.JButton();
        spMUser = new javax.swing.JScrollPane();
        tblMHead = new javax.swing.JTable();
        pfMUserPassword = new javax.swing.JPasswordField();
        lblMUserID = new javax.swing.JLabel();
        cbMUserShowPassword = new javax.swing.JCheckBox();
        lblMUserUsername = new javax.swing.JLabel();
        lblMUserDepartment = new javax.swing.JLabel();
        txtMUserDepartment = new javax.swing.JTextField();
        lblMUserError = new javax.swing.JLabel();
        btnMUserDelete = new javax.swing.JButton();
        lblMUserRole = new javax.swing.JLabel();
        cbMUserRole = new javax.swing.JComboBox<>();
        lblMUserDepartment1 = new javax.swing.JLabel();
        txtMUserDepartment1 = new javax.swing.JTextField();
        lblMUserEmail = new javax.swing.JLabel();
        txtMUserEmail = new javax.swing.JTextField();
        lblMUserContactNo = new javax.swing.JLabel();
        txtMUserContactNo = new javax.swing.JTextField();
        lblMUserAddress = new javax.swing.JLabel();
        txtMUserAddress = new javax.swing.JTextField();
        btnMUserEdit = new javax.swing.JButton();
        txtMUserSearch = new javax.swing.JTextField();
        btnMUserSearch = new javax.swing.JButton();
        pnlAccount = new javax.swing.JPanel();
        lblRAMRoomManagement1 = new javax.swing.JLabel();
        pnlAInformation = new javax.swing.JPanel();
        labelAID = new javax.swing.JLabel();
        labelAUsername = new javax.swing.JLabel();
        labelAFirstName = new javax.swing.JLabel();
        labelALastName = new javax.swing.JLabel();
        labelADepartment = new javax.swing.JLabel();
        btnALogout = new javax.swing.JButton();
        btnAChangePassword = new javax.swing.JButton();
        lblAID = new javax.swing.JLabel();
        lbAlUsername = new javax.swing.JLabel();
        lblAFirstname = new javax.swing.JLabel();
        lblALastname = new javax.swing.JLabel();
        lblADepartment = new javax.swing.JLabel();

        tpRAMStartTime.setForeground(new java.awt.Color(218, 104, 70));
        tpRAMStartTime.setDisplayText(txtRAMStartTime);
        tpRAMStartTime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        tpRAMEndTime.setForeground(new java.awt.Color(218, 104, 70));
        tpRAMEndTime.setDisplayText(txtRAMEndTime);
        tpRAMEndTime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tpRAMEndTime.setName(""); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("Dashboard"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setResizable(false);

        pnlTabLeft.setBackground(new java.awt.Color(251, 251, 251));

        pnlTabHome.setBackground(new java.awt.Color(218, 104, 70));
        pnlTabHome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTabHome.setPreferredSize(new java.awt.Dimension(105, 55));
        pnlTabHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTabHomeMouseClicked(evt);
            }
        });

        lblHome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/home.png"))); // NOI18N
        lblHome.setText("Home");

        javax.swing.GroupLayout pnlTabHomeLayout = new javax.swing.GroupLayout(pnlTabHome);
        pnlTabHome.setLayout(pnlTabHomeLayout);
        pnlTabHomeLayout.setHorizontalGroup(
            pnlTabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTabHomeLayout.setVerticalGroup(
            pnlTabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTabRoomManagement.setBackground(new java.awt.Color(218, 104, 70));
        pnlTabRoomManagement.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTabRoomManagement.setPreferredSize(new java.awt.Dimension(105, 55));
        pnlTabRoomManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTabRoomManagementMouseClicked(evt);
            }
        });

        lblTabRoomManagement.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTabRoomManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabRoomManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/lecture.png"))); // NOI18N
        lblTabRoomManagement.setText("Room Management");

        javax.swing.GroupLayout pnlTabRoomManagementLayout = new javax.swing.GroupLayout(pnlTabRoomManagement);
        pnlTabRoomManagement.setLayout(pnlTabRoomManagementLayout);
        pnlTabRoomManagementLayout.setHorizontalGroup(
            pnlTabRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabRoomManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTabRoomManagementLayout.setVerticalGroup(
            pnlTabRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabRoomManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTabMembers.setBackground(new java.awt.Color(218, 104, 70));
        pnlTabMembers.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTabMembers.setPreferredSize(new java.awt.Dimension(105, 55));
        pnlTabMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTabMembersMouseClicked(evt);
            }
        });

        lblTabMembers.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTabMembers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/group.png"))); // NOI18N
        lblTabMembers.setText("Members");

        javax.swing.GroupLayout pnlTabMembersLayout = new javax.swing.GroupLayout(pnlTabMembers);
        pnlTabMembers.setLayout(pnlTabMembersLayout);
        pnlTabMembersLayout.setHorizontalGroup(
            pnlTabMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTabMembersLayout.setVerticalGroup(
            pnlTabMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabMembersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTabAccount.setBackground(new java.awt.Color(218, 104, 70));
        pnlTabAccount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTabAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTabAccountMouseClicked(evt);
            }
        });

        lblTabAccount.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTabAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/user.png"))); // NOI18N
        lblTabAccount.setText("Account");

        javax.swing.GroupLayout pnlTabAccountLayout = new javax.swing.GroupLayout(pnlTabAccount);
        pnlTabAccount.setLayout(pnlTabAccountLayout);
        pnlTabAccountLayout.setHorizontalGroup(
            pnlTabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTabAccountLayout.setVerticalGroup(
            pnlTabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblImageOnTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/undraw_Launching.png"))); // NOI18N

        lblRoomMangementSystem.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 12)); // NOI18N
        lblRoomMangementSystem.setText("Room Management System");

        javax.swing.GroupLayout pnlTabLeftLayout = new javax.swing.GroupLayout(pnlTabLeft);
        pnlTabLeft.setLayout(pnlTabLeftLayout);
        pnlTabLeftLayout.setHorizontalGroup(
            pnlTabLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTabHome, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
            .addComponent(pnlTabRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
            .addComponent(pnlTabMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
            .addComponent(pnlTabAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabLeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImageOnTop)
                .addGap(61, 61, 61))
            .addGroup(pnlTabLeftLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblRoomMangementSystem)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlTabLeftLayout.setVerticalGroup(
            pnlTabLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabLeftLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblImageOnTop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRoomMangementSystem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(pnlTabHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTabRoomManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTabMembers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTabAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        pnlTabRight.setBackground(new java.awt.Color(204, 204, 204));

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));

        pnlHomeCreatedSchedule.setBackground(java.awt.Color.darkGray);

        lblHomeCreatedSchedule.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblHomeCreatedSchedule.setForeground(java.awt.Color.white);
        lblHomeCreatedSchedule.setText("Created Schedule");

        lblHomeScheduleNumber.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblHomeScheduleNumber.setForeground(java.awt.Color.white);
        lblHomeScheduleNumber.setText("00");

        javax.swing.GroupLayout pnlHomeCreatedScheduleLayout = new javax.swing.GroupLayout(pnlHomeCreatedSchedule);
        pnlHomeCreatedSchedule.setLayout(pnlHomeCreatedScheduleLayout);
        pnlHomeCreatedScheduleLayout.setHorizontalGroup(
            pnlHomeCreatedScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeCreatedScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeCreatedScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHomeScheduleNumber)
                    .addComponent(lblHomeCreatedSchedule))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        pnlHomeCreatedScheduleLayout.setVerticalGroup(
            pnlHomeCreatedScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeCreatedScheduleLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblHomeScheduleNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHomeCreatedSchedule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHomeCreatedAccount.setBackground(java.awt.Color.darkGray);

        lblHomeCreatedAccount.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblHomeCreatedAccount.setForeground(java.awt.Color.white);
        lblHomeCreatedAccount.setText("Created Account");

        lblHomeAccountNumber.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblHomeAccountNumber.setForeground(java.awt.Color.white);
        lblHomeAccountNumber.setText("00");

        javax.swing.GroupLayout pnlHomeCreatedAccountLayout = new javax.swing.GroupLayout(pnlHomeCreatedAccount);
        pnlHomeCreatedAccount.setLayout(pnlHomeCreatedAccountLayout);
        pnlHomeCreatedAccountLayout.setHorizontalGroup(
            pnlHomeCreatedAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeCreatedAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeCreatedAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHomeAccountNumber)
                    .addComponent(lblHomeCreatedAccount))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnlHomeCreatedAccountLayout.setVerticalGroup(
            pnlHomeCreatedAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeCreatedAccountLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblHomeAccountNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHomeCreatedAccount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHomeFacultiesStudents.setBackground(java.awt.Color.darkGray);

        lblHomeFaculties.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblHomeFaculties.setForeground(java.awt.Color.white);
        lblHomeFaculties.setText("Faculties");

        lblHomeFacultiesNumber.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblHomeFacultiesNumber.setForeground(java.awt.Color.white);
        lblHomeFacultiesNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeFacultiesNumber.setText("00");

        javax.swing.GroupLayout pnlHomeFacultiesStudentsLayout = new javax.swing.GroupLayout(pnlHomeFacultiesStudents);
        pnlHomeFacultiesStudents.setLayout(pnlHomeFacultiesStudentsLayout);
        pnlHomeFacultiesStudentsLayout.setHorizontalGroup(
            pnlHomeFacultiesStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeFacultiesStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeFacultiesStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblHomeFacultiesNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHomeFaculties, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        pnlHomeFacultiesStudentsLayout.setVerticalGroup(
            pnlHomeFacultiesStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeFacultiesStudentsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblHomeFacultiesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHomeFaculties)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnlHomeActivityLog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Activity Log", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N

        listActivityLog.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        listActivityLog.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "This User Delete ID: 000", "This User Edit ID: 000", "This User Create ID: 000", "This User Delete ID: 000", "This User Delete ID: 000", "This User Delete ID: 000", "This User Create ID: 000", "This User Delete ID: 000", "This User Edit ID: 000", "This User Delete ID: 000", "This User Create ID: 000", "This User Delete ID: 000", "This User Create ID: 000", "This User Edit ID: 000", "This User Delete ID: 000", "This User Edit ID: 000" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spActivityLog.setViewportView(listActivityLog);

        javax.swing.GroupLayout pnlHomeActivityLogLayout = new javax.swing.GroupLayout(pnlHomeActivityLog);
        pnlHomeActivityLog.setLayout(pnlHomeActivityLogLayout);
        pnlHomeActivityLogLayout.setHorizontalGroup(
            pnlHomeActivityLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeActivityLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spActivityLog)
                .addContainerGap())
        );
        pnlHomeActivityLogLayout.setVerticalGroup(
            pnlHomeActivityLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeActivityLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spActivityLog)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlHomeFacultiesStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlHomeCreatedSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlHomeCreatedAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHomeActivityLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlHomeCreatedAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHomeCreatedSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHomeFacultiesStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119)
                .addComponent(pnlHomeActivityLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlRoomManagement.setBackground(new java.awt.Color(204, 204, 204));
        pnlRoomManagement.setMaximumSize(new java.awt.Dimension(838, 523));
        pnlRoomManagement.setMinimumSize(new java.awt.Dimension(838, 523));

        lblRAMRoomManagement.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblRAMRoomManagement.setText("Room Assignment & Management");

        pnlRAMSchedule.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schedule", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 3, 14))); // NOI18N

        tblRAMShowRoom.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblRAMShowRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Schedule ID", "Room", "Subject", "Section", "Teacher", "Day of the Week", "Start Time", "End Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spRAMShowRoom.setViewportView(tblRAMShowRoom);

        lblRAMID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblRAMID.setText("Schedule ID");

        lblRAMSubject.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblRAMSubject.setText("Subject");

        lblRAMSection.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblRAMSection.setText("Section");

        lblRAMDayOfTheWeek.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblRAMDayOfTheWeek.setText("Day of the Week");

        lblRAMStartTime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblRAMStartTime.setText("Start Time");

        lblRAMEndTime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblRAMEndTime.setText("End Time");

        txtRAMID.setEditable(false);
        txtRAMID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtRAMSubject.setEditable(false);
        txtRAMSubject.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        txtRAMSection.setEditable(false);
        txtRAMSection.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnRAMSave.setBackground(new java.awt.Color(218, 104, 70));
        btnRAMSave.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRAMSave.setText("Save");
        btnRAMSave.setBorder(null);
        btnRAMSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAMSaveActionPerformed(evt);
            }
        });

        btnRAMAddNew.setBackground(new java.awt.Color(218, 104, 70));
        btnRAMAddNew.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRAMAddNew.setText("Add New?");
        btnRAMAddNew.setBorder(null);
        btnRAMAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAMAddNewActionPerformed(evt);
            }
        });

        txtRAMStartTime.setEditable(false);
        txtRAMStartTime.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtRAMStartTime.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtRAMStartTimeInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        txtRAMEndTime.setEditable(false);
        txtRAMEndTime.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnRAMStartTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/clock.png"))); // NOI18N
        btnRAMStartTime.setBorder(null);
        btnRAMStartTime.setEnabled(false);
        btnRAMStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAMStartTimeActionPerformed(evt);
            }
        });

        btnRAMEndTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/clock.png"))); // NOI18N
        btnRAMEndTime.setBorder(null);
        btnRAMEndTime.setEnabled(false);
        btnRAMEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAMEndTimeActionPerformed(evt);
            }
        });

        lblRAMError.setForeground(java.awt.Color.red);
        lblRAMError.setText("[error appear here]");

        btnRAMDeleteRoom.setBackground(new java.awt.Color(204, 0, 0));
        btnRAMDeleteRoom.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRAMDeleteRoom.setForeground(java.awt.Color.white);
        btnRAMDeleteRoom.setText("Delete");
        btnRAMDeleteRoom.setBorder(null);
        btnRAMDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAMDeleteRoomActionPerformed(evt);
            }
        });

        lblRAMRoom.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblRAMRoom.setText("Room");

        txtRAMRoom.setEditable(false);
        txtRAMRoom.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        cbRAMDayOfTheWeek.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbRAMDayOfTheWeek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }));

        lblRAMTeacher.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblRAMTeacher.setText("Teacher");

        txtRAMTeacher.setEditable(false);
        txtRAMTeacher.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnRAMEdit.setBackground(new java.awt.Color(218, 104, 70));
        btnRAMEdit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRAMEdit.setForeground(new java.awt.Color(51, 51, 51));
        btnRAMEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/lock.png"))); // NOI18N
        btnRAMEdit.setText("Edit");
        btnRAMEdit.setBorder(null);
        btnRAMEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAMEditActionPerformed(evt);
            }
        });

        txtRAMSearch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnRAMSearch.setBackground(new java.awt.Color(218, 104, 70));
        btnRAMSearch.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRAMSearch.setForeground(new java.awt.Color(51, 51, 51));
        btnRAMSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/search.png"))); // NOI18N
        btnRAMSearch.setText("Search");
        btnRAMSearch.setBorder(null);
        btnRAMSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAMSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRAMScheduleLayout = new javax.swing.GroupLayout(pnlRAMSchedule);
        pnlRAMSchedule.setLayout(pnlRAMScheduleLayout);
        pnlRAMScheduleLayout.setHorizontalGroup(
            pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblRAMID)
                        .addGap(4, 4, 4)
                        .addComponent(txtRAMID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRAMTeacher)
                        .addGap(50, 50, 50)
                        .addComponent(txtRAMTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblRAMRoom)
                        .addGap(40, 40, 40)
                        .addComponent(txtRAMRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRAMDayOfTheWeek)
                        .addGap(4, 4, 4)
                        .addComponent(cbRAMDayOfTheWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblRAMSubject)
                        .addGap(31, 31, 31)
                        .addComponent(txtRAMSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRAMStartTime)
                        .addGap(44, 44, 44)
                        .addComponent(txtRAMStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnRAMStartTime))
                    .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblRAMSection)
                        .addGap(31, 31, 31)
                        .addComponent(txtRAMSection, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRAMEndTime)
                        .addGap(47, 47, 47)
                        .addComponent(txtRAMEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnRAMEndTime))
                    .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblRAMError, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtRAMSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnRAMSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnRAMSave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnRAMAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnRAMEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnRAMDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spRAMShowRoom)
                .addContainerGap())
        );
        pnlRAMScheduleLayout.setVerticalGroup(
            pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRAMID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRAMTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRAMID)
                            .addComponent(lblRAMTeacher))))
                .addGap(6, 6, 6)
                .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRAMRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRAMDayOfTheWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRAMRoom)
                            .addComponent(lblRAMDayOfTheWeek))))
                .addGap(6, 6, 6)
                .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRAMSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRAMStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRAMStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRAMSubject)
                            .addComponent(lblRAMStartTime))))
                .addGap(6, 6, 6)
                .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRAMSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRAMEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRAMEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRAMScheduleLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRAMSection)
                            .addComponent(lblRAMEndTime))))
                .addGap(12, 12, 12)
                .addComponent(lblRAMError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRAMScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRAMSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(btnRAMSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnRAMSave, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRAMAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRAMEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRAMDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(spRAMShowRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlRoomManagementLayout = new javax.swing.GroupLayout(pnlRoomManagement);
        pnlRoomManagement.setLayout(pnlRoomManagementLayout);
        pnlRoomManagementLayout.setHorizontalGroup(
            pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRoomManagementLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRoomManagementLayout.createSequentialGroup()
                        .addComponent(lblRAMRoomManagement)
                        .addGap(526, 526, 526))
                    .addGroup(pnlRoomManagementLayout.createSequentialGroup()
                        .addComponent(pnlRAMSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 818, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlRoomManagementLayout.setVerticalGroup(
            pnlRoomManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRoomManagementLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblRAMRoomManagement)
                .addGap(11, 11, 11)
                .addComponent(pnlRAMSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlMembers.setBackground(new java.awt.Color(204, 204, 204));
        pnlMembers.setMaximumSize(new java.awt.Dimension(838, 523));
        pnlMembers.setMinimumSize(new java.awt.Dimension(838, 523));
        pnlMembers.setPreferredSize(new java.awt.Dimension(838, 523));
        pnlMembers.setLayout(null);

        lblMMember.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblMMember.setText("Members");
        pnlMembers.add(lblMMember);
        lblMMember.setBounds(10, 11, 83, 24);

        pnlMViewUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 3, 14))); // NOI18N
        pnlMViewUser.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        pnlMViewUser.setLayout(null);

        lblMUserFirstName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserFirstName.setText("First Name");
        pnlMViewUser.add(lblMUserFirstName);
        lblMUserFirstName.setBounds(392, 24, 60, 16);

        lblMUserLastName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserLastName.setText("Last Name");
        pnlMViewUser.add(lblMUserLastName);
        lblMUserLastName.setBounds(392, 52, 60, 16);

        lblMUserPassword.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserPassword.setText("Password");
        pnlMViewUser.add(lblMUserPassword);
        lblMUserPassword.setBounds(16, 70, 55, 16);

        txtMUserID.setEditable(false);
        txtMUserID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pnlMViewUser.add(txtMUserID);
        txtMUserID.setBounds(88, 21, 260, 22);

        btnMUserSave.setBackground(new java.awt.Color(218, 104, 70));
        btnMUserSave.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnMUserSave.setForeground(new java.awt.Color(51, 51, 51));
        btnMUserSave.setText("Save");
        btnMUserSave.setBorder(null);
        btnMUserSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUserSaveActionPerformed(evt);
            }
        });
        pnlMViewUser.add(btnMUserSave);
        btnMUserSave.setBounds(424, 240, 81, 28);

        txtMUserUsername.setEditable(false);
        txtMUserUsername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pnlMViewUser.add(txtMUserUsername);
        txtMUserUsername.setBounds(88, 49, 259, 22);

        txtMUserFirstName.setEditable(false);
        txtMUserFirstName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pnlMViewUser.add(txtMUserFirstName);
        txtMUserFirstName.setBounds(476, 21, 259, 22);

        txtMUserLastName.setEditable(false);
        txtMUserLastName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pnlMViewUser.add(txtMUserLastName);
        txtMUserLastName.setBounds(476, 49, 259, 22);

        btnMUserAddNew.setBackground(new java.awt.Color(218, 104, 70));
        btnMUserAddNew.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnMUserAddNew.setForeground(new java.awt.Color(51, 51, 51));
        btnMUserAddNew.setText("Add New?");
        btnMUserAddNew.setBorder(null);
        btnMUserAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUserAddNewActionPerformed(evt);
            }
        });
        pnlMViewUser.add(btnMUserAddNew);
        btnMUserAddNew.setBounds(511, 240, 89, 28);

        tblMHead.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblMHead.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Password", "Department", "Roles", "First Name", "Last Name", "Middle Name", "Email", "Contact No.", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMHead.setOpaque(false);
        tblMHead.setRequestFocusEnabled(false);
        spMUser.setViewportView(tblMHead);

        pnlMViewUser.add(spMUser);
        spMUser.setBounds(16, 274, 786, 170);

        pfMUserPassword.setEditable(false);
        pfMUserPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pfMUserPassword.setText("jPasswordField1");
        pnlMViewUser.add(pfMUserPassword);
        pfMUserPassword.setBounds(88, 76, 259, 22);

        lblMUserID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserID.setText("User ID");
        pnlMViewUser.add(lblMUserID);
        lblMUserID.setBounds(16, 21, 40, 16);

        cbMUserShowPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbMUserShowPassword.setText("Show Password");
        cbMUserShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMUserShowPasswordActionPerformed(evt);
            }
        });
        pnlMViewUser.add(cbMUserShowPassword);
        cbMUserShowPassword.setBounds(88, 100, 115, 25);

        lblMUserUsername.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserUsername.setText("Username");
        pnlMViewUser.add(lblMUserUsername);
        lblMUserUsername.setBounds(16, 43, 59, 16);

        lblMUserDepartment.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserDepartment.setText("Department");
        pnlMViewUser.add(lblMUserDepartment);
        lblMUserDepartment.setBounds(16, 126, 68, 16);

        txtMUserDepartment.setEditable(false);
        txtMUserDepartment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pnlMViewUser.add(txtMUserDepartment);
        txtMUserDepartment.setBounds(88, 132, 259, 22);

        lblMUserError.setForeground(java.awt.Color.red);
        lblMUserError.setText("[error appear here]");
        pnlMViewUser.add(lblMUserError);
        lblMUserError.setBounds(16, 199, 360, 14);

        btnMUserDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnMUserDelete.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnMUserDelete.setForeground(java.awt.Color.white);
        btnMUserDelete.setText("Delete");
        btnMUserDelete.setBorder(null);
        btnMUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUserDeleteActionPerformed(evt);
            }
        });
        pnlMViewUser.add(btnMUserDelete);
        btnMUserDelete.setBounds(713, 240, 89, 28);

        lblMUserRole.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserRole.setText("Role");
        pnlMViewUser.add(lblMUserRole);
        lblMUserRole.setBounds(16, 160, 26, 16);

        cbMUserRole.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cbMUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher", "Program Head", "Administrator" }));
        pnlMViewUser.add(cbMUserRole);
        cbMUserRole.setBounds(88, 158, 259, 21);

        lblMUserDepartment1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserDepartment1.setText("Middle Name");
        pnlMViewUser.add(lblMUserDepartment1);
        lblMUserDepartment1.setBounds(392, 79, 80, 16);

        txtMUserDepartment1.setEditable(false);
        txtMUserDepartment1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pnlMViewUser.add(txtMUserDepartment1);
        txtMUserDepartment1.setBounds(476, 76, 259, 22);

        lblMUserEmail.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserEmail.setText("Email");
        pnlMViewUser.add(lblMUserEmail);
        lblMUserEmail.setBounds(392, 107, 31, 16);

        txtMUserEmail.setEditable(false);
        txtMUserEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pnlMViewUser.add(txtMUserEmail);
        txtMUserEmail.setBounds(476, 104, 259, 22);

        lblMUserContactNo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserContactNo.setText("Contact No.");
        pnlMViewUser.add(lblMUserContactNo);
        lblMUserContactNo.setBounds(392, 135, 69, 16);

        txtMUserContactNo.setEditable(false);
        txtMUserContactNo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pnlMViewUser.add(txtMUserContactNo);
        txtMUserContactNo.setBounds(476, 132, 259, 22);

        lblMUserAddress.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblMUserAddress.setText("Address");
        pnlMViewUser.add(lblMUserAddress);
        lblMUserAddress.setBounds(392, 165, 47, 16);

        txtMUserAddress.setEditable(false);
        txtMUserAddress.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pnlMViewUser.add(txtMUserAddress);
        txtMUserAddress.setBounds(476, 165, 260, 49);

        btnMUserEdit.setBackground(new java.awt.Color(218, 104, 70));
        btnMUserEdit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnMUserEdit.setForeground(new java.awt.Color(51, 51, 51));
        btnMUserEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/lock.png"))); // NOI18N
        btnMUserEdit.setText("Edit");
        btnMUserEdit.setBorder(null);
        btnMUserEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUserEditActionPerformed(evt);
            }
        });
        pnlMViewUser.add(btnMUserEdit);
        btnMUserEdit.setBounds(606, 240, 89, 28);

        txtMUserSearch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pnlMViewUser.add(txtMUserSearch);
        txtMUserSearch.setBounds(16, 240, 259, 28);

        btnMUserSearch.setBackground(new java.awt.Color(218, 104, 70));
        btnMUserSearch.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnMUserSearch.setForeground(new java.awt.Color(51, 51, 51));
        btnMUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssignment/image/search.png"))); // NOI18N
        btnMUserSearch.setText("Search");
        btnMUserSearch.setBorder(null);
        btnMUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUserSearchActionPerformed(evt);
            }
        });
        pnlMViewUser.add(btnMUserSearch);
        btnMUserSearch.setBounds(281, 240, 104, 28);

        pnlMembers.add(pnlMViewUser);
        pnlMViewUser.setBounds(10, 53, 818, 459);

        pnlAccount.setBackground(new java.awt.Color(204, 204, 204));

        lblRAMRoomManagement1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblRAMRoomManagement1.setText("Account");

        pnlAInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N

        labelAID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelAID.setText("ID");

        labelAUsername.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelAUsername.setText("Username");

        labelAFirstName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelAFirstName.setText("First Name");

        labelALastName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelALastName.setText("Last Name");

        labelADepartment.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelADepartment.setText("Department");

        btnALogout.setBackground(new java.awt.Color(218, 104, 70));
        btnALogout.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnALogout.setForeground(new java.awt.Color(51, 51, 51));
        btnALogout.setText("Logout?");
        btnALogout.setBorder(null);
        btnALogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALogoutActionPerformed(evt);
            }
        });

        btnAChangePassword.setBackground(new java.awt.Color(218, 104, 70));
        btnAChangePassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAChangePassword.setForeground(new java.awt.Color(51, 51, 51));
        btnAChangePassword.setText("Change Password?");
        btnAChangePassword.setBorder(null);
        btnAChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAChangePasswordActionPerformed(evt);
            }
        });

        lblAID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblAID.setText("Sample ID");
        lblAID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lbAlUsername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbAlUsername.setText("Sample Username");
        lbAlUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblAFirstname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblAFirstname.setText("Sample First Name");
        lblAFirstname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblALastname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblALastname.setText("Sample Last Name");
        lblALastname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblADepartment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblADepartment.setText("Sample Department");
        lblADepartment.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlAInformationLayout = new javax.swing.GroupLayout(pnlAInformation);
        pnlAInformation.setLayout(pnlAInformationLayout);
        pnlAInformationLayout.setHorizontalGroup(
            pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAInformationLayout.createSequentialGroup()
                        .addComponent(btnAChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(btnALogout, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAInformationLayout.createSequentialGroup()
                        .addGroup(pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAUsername)
                            .addComponent(labelAID))
                        .addGap(35, 35, 35)
                        .addGroup(pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAlUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlAInformationLayout.createSequentialGroup()
                        .addComponent(labelADepartment)
                        .addGap(26, 26, 26)
                        .addComponent(lblADepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlAInformationLayout.createSequentialGroup()
                        .addComponent(labelAFirstName)
                        .addGap(34, 34, 34)
                        .addComponent(lblAFirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlAInformationLayout.createSequentialGroup()
                        .addComponent(labelALastName)
                        .addGap(34, 34, 34)
                        .addComponent(lblALastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAInformationLayout.setVerticalGroup(
            pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAID)
                    .addComponent(lblAID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAUsername)
                    .addComponent(lbAlUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAFirstName)
                    .addComponent(lblAFirstname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelALastName)
                    .addComponent(lblALastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelADepartment)
                    .addComponent(lblADepartment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(pnlAInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnALogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlAccountLayout = new javax.swing.GroupLayout(pnlAccount);
        pnlAccount.setLayout(pnlAccountLayout);
        pnlAccountLayout.setHorizontalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRAMRoomManagement1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(pnlAInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        pnlAccountLayout.setVerticalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRAMRoomManagement1)
                .addGap(82, 82, 82)
                .addComponent(pnlAInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTabRightLayout = new javax.swing.GroupLayout(pnlTabRight);
        pnlTabRight.setLayout(pnlTabRightLayout);
        pnlTabRightLayout.setHorizontalGroup(
            pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlTabRightLayout.setVerticalGroup(
            pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlRoomManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlTabRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTabRightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTabLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTabLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTabRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTabHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTabHomeMouseClicked
        HomeTab();
    }//GEN-LAST:event_pnlTabHomeMouseClicked

    private void pnlTabRoomManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTabRoomManagementMouseClicked
        RoomManagementTab();
    }//GEN-LAST:event_pnlTabRoomManagementMouseClicked

    private void pnlTabMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTabMembersMouseClicked
        MemberTab();
    }//GEN-LAST:event_pnlTabMembersMouseClicked

    private void pnlTabAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTabAccountMouseClicked
        AccountTab();
    }//GEN-LAST:event_pnlTabAccountMouseClicked

    private void btnRAMSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAMSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRAMSaveActionPerformed

    private void btnRAMAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAMAddNewActionPerformed
        Add_Room ar = new Add_Room();
        ar.show();
    }//GEN-LAST:event_btnRAMAddNewActionPerformed

    private void btnRAMStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAMStartTimeActionPerformed
        tpRAMStartTime.showPopup(this, 100, 100);
    }//GEN-LAST:event_btnRAMStartTimeActionPerformed

    private void txtRAMStartTimeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtRAMStartTimeInputMethodTextChanged
        
    }//GEN-LAST:event_txtRAMStartTimeInputMethodTextChanged

    private void btnRAMEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAMEndTimeActionPerformed
        tpRAMEndTime.showPopup(this, 100, 100);
    }//GEN-LAST:event_btnRAMEndTimeActionPerformed

    private void btnRAMDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAMDeleteRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRAMDeleteRoomActionPerformed

    private void btnMUserSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUserSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMUserSaveActionPerformed

    private void btnMUserAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUserAddNewActionPerformed
        Add_User aph = new Add_User();
        aph.show();
        aph.setAlwaysOnTop(true);
    }//GEN-LAST:event_btnMUserAddNewActionPerformed

    private void cbMUserShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMUserShowPasswordActionPerformed
         if(cbMUserShowPassword.isSelected()){
            pfMUserPassword.setEchoChar((char) 0);
        }else{
            pfMUserPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_cbMUserShowPasswordActionPerformed

    private void btnALogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALogoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnALogoutActionPerformed

    private void btnMUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUserDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMUserDeleteActionPerformed

    private void btnAChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAChangePasswordActionPerformed
        Change_Password cp = new Change_Password();
        cp.show();
        cp.setAlwaysOnTop(true);
    }//GEN-LAST:event_btnAChangePasswordActionPerformed

    private void btnMUserEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUserEditActionPerformed
        MEdit();
    }//GEN-LAST:event_btnMUserEditActionPerformed

    private void btnRAMEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAMEditActionPerformed
        RAMEdit();
    }//GEN-LAST:event_btnRAMEditActionPerformed

    private void btnMUserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUserSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMUserSearchActionPerformed

    private void btnRAMSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAMSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRAMSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public void DefaultTab(){
        pnlHome.setVisible(true);
        pnlRoomManagement.setVisible(false);
        pnlMembers.setVisible(false);
        pnlAccount.setVisible(false);
        
        pnlTabHome.setBackground(new Color(247, 246, 220));
        pnlTabRoomManagement.setBackground(new Color(218,104,70));
        pnlTabMembers.setBackground(new Color(218,104,70));
        pnlTabAccount.setBackground(new Color(218,104,70));
    }
    public void HomeTab(){
        pnlHome.setVisible(true);
        pnlRoomManagement.setVisible(false);
        pnlMembers.setVisible(false);
        pnlAccount.setVisible(false);
        
        pnlTabHome.setBackground(new Color(247, 246, 220));
        pnlTabRoomManagement.setBackground(new Color(218,104,70));
        pnlTabMembers.setBackground(new Color(218,104,70));
        pnlTabAccount.setBackground(new Color(218,104,70));
    }
    public void RoomManagementTab(){
        pnlRoomManagement.setVisible(true);
        pnlHome.setVisible(false);
        pnlMembers.setVisible(false);
        pnlAccount.setVisible(false);
        
        pnlTabRoomManagement.setBackground(new Color(247, 246, 220));
        pnlTabHome.setBackground(new Color(218,104,70));
        pnlTabMembers.setBackground(new Color(218,104,70));
        pnlTabAccount.setBackground(new Color(218,104,70));
    }
    public void MemberTab(){
        pnlMembers.setVisible(true);
        pnlHome.setVisible(false);
        pnlRoomManagement.setVisible(false);
        pnlAccount.setVisible(false);
        pnlMViewUser.setVisible(true);
        
        pnlTabMembers.setBackground(new Color(247, 246, 220));
        pnlTabHome.setBackground(new Color(218,104,70));
        pnlTabRoomManagement.setBackground(new Color(218,104,70));
        pnlTabAccount.setBackground(new Color(218,104,70));
    }
    public void AccountTab(){
        pnlAccount.setVisible(true);
        pnlHome.setVisible(false);
        pnlRoomManagement.setVisible(false);
        pnlMembers.setVisible(false);
        
        pnlTabAccount.setBackground(new Color(247, 246, 220));
        pnlTabHome.setBackground(new Color(218,104,70));
        pnlTabRoomManagement.setBackground(new Color(218,104,70));
        pnlTabMembers.setBackground(new Color(218,104,70));
    }
    public void RAMEdit(){
        boolean ID = txtRAMID.isEditable();
        boolean Room = txtRAMRoom.isEditable();
        boolean Subject = txtRAMSubject.isEditable();
        boolean Section = txtRAMSection.isEditable();
        boolean Teacher = txtRAMTeacher.isEditable();
        boolean dotw = cbRAMDayOfTheWeek.isEditable();
        boolean st = txtRAMStartTime.isEditable();
        boolean et = txtRAMEndTime.isEditable();
        boolean btnST = btnRAMStartTime.isEnabled();
        boolean btnET = btnRAMEndTime.isEnabled();
        
        Icon unlock = new ImageIcon("C:\\Users\\solve\\Documents\\NetBeansProjects\\RoomAssignmentManagementSystem\\src\\RoomAssignment\\image\\unlock.png");
        Icon lock = new ImageIcon("C:\\Users\\solve\\Documents\\NetBeansProjects\\RoomAssignmentManagementSystem\\src\\RoomAssignment\\image\\lock.png");
        
        if(ID == false && Room == false && Subject == false && Section == false && Teacher == false && dotw == false && st == false && et == false && btnST == false && btnET == false){
            btnRAMEdit.setIcon(unlock);
            btnRAMEdit.setBackground(new Color(153,153,153));
            txtRAMID.setEditable(true);
            txtRAMRoom.setEditable(true);
            txtRAMSubject.setEditable(true);
            txtRAMSection.setEditable(true);
            txtRAMTeacher.setEditable(true);
            cbRAMDayOfTheWeek.setEditable(true);
            txtRAMStartTime.setEditable(true);
            txtRAMEndTime.setEditable(true);
            btnRAMStartTime.setEnabled(true);
            btnRAMEndTime.setEnabled(true);
        }else if(ID == true && Room == true && Subject == true && Section == true && Teacher == true && dotw == true && st == true && et == true && btnST == true && btnET == true){
            btnRAMEdit.setIcon(lock);
            btnRAMEdit.setBackground(new Color(218,104,70));
            txtRAMID.setEditable(false);
            txtRAMRoom.setEditable(false);
            txtRAMSubject.setEditable(false);
            txtRAMSection.setEditable(false);
            txtRAMTeacher.setEditable(false);
            cbRAMDayOfTheWeek.setEditable(false);
            txtRAMStartTime.setEditable(false);
            txtRAMEndTime.setEditable(false);
            btnRAMStartTime.setEnabled(false);
            btnRAMEndTime.setEnabled(false);
        }
        
        
    }
    public void MEdit(){
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAChangePassword;
    private javax.swing.JButton btnALogout;
    private javax.swing.JButton btnMUserAddNew;
    private javax.swing.JButton btnMUserDelete;
    private javax.swing.JButton btnMUserEdit;
    private javax.swing.JButton btnMUserSave;
    private javax.swing.JButton btnMUserSearch;
    private javax.swing.JButton btnRAMAddNew;
    private javax.swing.JButton btnRAMDeleteRoom;
    private javax.swing.JButton btnRAMEdit;
    private javax.swing.JButton btnRAMEndTime;
    private javax.swing.JButton btnRAMSave;
    private javax.swing.JButton btnRAMSearch;
    private javax.swing.JButton btnRAMStartTime;
    private javax.swing.JComboBox<String> cbMUserRole;
    private javax.swing.JCheckBox cbMUserShowPassword;
    private javax.swing.JComboBox<String> cbRAMDayOfTheWeek;
    private javax.swing.JLabel labelADepartment;
    private javax.swing.JLabel labelAFirstName;
    private javax.swing.JLabel labelAID;
    private javax.swing.JLabel labelALastName;
    private javax.swing.JLabel labelAUsername;
    private javax.swing.JLabel lbAlUsername;
    private javax.swing.JLabel lblADepartment;
    private javax.swing.JLabel lblAFirstname;
    private javax.swing.JLabel lblAID;
    private javax.swing.JLabel lblALastname;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHomeAccountNumber;
    private javax.swing.JLabel lblHomeCreatedAccount;
    private javax.swing.JLabel lblHomeCreatedSchedule;
    private javax.swing.JLabel lblHomeFaculties;
    private javax.swing.JLabel lblHomeFacultiesNumber;
    private javax.swing.JLabel lblHomeScheduleNumber;
    private javax.swing.JLabel lblImageOnTop;
    private javax.swing.JLabel lblMMember;
    private javax.swing.JLabel lblMUserAddress;
    private javax.swing.JLabel lblMUserContactNo;
    private javax.swing.JLabel lblMUserDepartment;
    private javax.swing.JLabel lblMUserDepartment1;
    private javax.swing.JLabel lblMUserEmail;
    private javax.swing.JLabel lblMUserError;
    private javax.swing.JLabel lblMUserFirstName;
    private javax.swing.JLabel lblMUserID;
    private javax.swing.JLabel lblMUserLastName;
    private javax.swing.JLabel lblMUserPassword;
    private javax.swing.JLabel lblMUserRole;
    private javax.swing.JLabel lblMUserUsername;
    private javax.swing.JLabel lblRAMDayOfTheWeek;
    private javax.swing.JLabel lblRAMEndTime;
    private javax.swing.JLabel lblRAMError;
    private javax.swing.JLabel lblRAMID;
    private javax.swing.JLabel lblRAMRoom;
    private javax.swing.JLabel lblRAMRoomManagement;
    private javax.swing.JLabel lblRAMRoomManagement1;
    private javax.swing.JLabel lblRAMSection;
    private javax.swing.JLabel lblRAMStartTime;
    private javax.swing.JLabel lblRAMSubject;
    private javax.swing.JLabel lblRAMTeacher;
    private javax.swing.JLabel lblRoomMangementSystem;
    private javax.swing.JLabel lblTabAccount;
    private javax.swing.JLabel lblTabMembers;
    private javax.swing.JLabel lblTabRoomManagement;
    private javax.swing.JList<String> listActivityLog;
    private javax.swing.JPasswordField pfMUserPassword;
    private javax.swing.JPanel pnlAInformation;
    private javax.swing.JPanel pnlAccount;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlHomeActivityLog;
    private javax.swing.JPanel pnlHomeCreatedAccount;
    private javax.swing.JPanel pnlHomeCreatedSchedule;
    private javax.swing.JPanel pnlHomeFacultiesStudents;
    private javax.swing.JPanel pnlMViewUser;
    private javax.swing.JPanel pnlMembers;
    private javax.swing.JPanel pnlRAMSchedule;
    private javax.swing.JPanel pnlRoomManagement;
    private javax.swing.JPanel pnlTabAccount;
    private javax.swing.JPanel pnlTabHome;
    private javax.swing.JPanel pnlTabLeft;
    private javax.swing.JPanel pnlTabMembers;
    private javax.swing.JPanel pnlTabRight;
    private javax.swing.JPanel pnlTabRoomManagement;
    private javax.swing.JScrollPane spActivityLog;
    private javax.swing.JScrollPane spMUser;
    private javax.swing.JScrollPane spRAMShowRoom;
    private javax.swing.JTable tblMHead;
    private javax.swing.JTable tblRAMShowRoom;
    private com.raven.swing.TimePicker tpRAMEndTime;
    private com.raven.swing.TimePicker tpRAMStartTime;
    private javax.swing.JTextField txtMUserAddress;
    private javax.swing.JTextField txtMUserContactNo;
    private javax.swing.JTextField txtMUserDepartment;
    private javax.swing.JTextField txtMUserDepartment1;
    private javax.swing.JTextField txtMUserEmail;
    private javax.swing.JTextField txtMUserFirstName;
    private javax.swing.JTextField txtMUserID;
    private javax.swing.JTextField txtMUserLastName;
    private javax.swing.JTextField txtMUserSearch;
    private javax.swing.JTextField txtMUserUsername;
    private javax.swing.JTextField txtRAMEndTime;
    private javax.swing.JTextField txtRAMID;
    private javax.swing.JTextField txtRAMRoom;
    private javax.swing.JTextField txtRAMSearch;
    private javax.swing.JTextField txtRAMSection;
    private javax.swing.JTextField txtRAMStartTime;
    private javax.swing.JTextField txtRAMSubject;
    private javax.swing.JTextField txtRAMTeacher;
    // End of variables declaration//GEN-END:variables
}
